"""initial

Revision ID: 2d77c318383b
Revises: 
Create Date: 2026-06-02 16:46:30.934081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d77c318383b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audience_segments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_itinerary_tolerance', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('scan_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('scanner_version', sa.String(), nullable=False),
    sa.Column('templates_scanned', sa.Integer(), nullable=False),
    sa.Column('routes_scanned', sa.Integer(), nullable=False),
    sa.Column('api_calls', sa.Integer(), nullable=False),
    sa.Column('http_429s', sa.Integer(), nullable=False),
    sa.Column('candidates_found', sa.Integer(), nullable=False),
    sa.Column('matches_created', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('travel_moments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('moment_type', sa.String(), nullable=False),
    sa.Column('default_content_angle', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('zones',
    sa.Column('zone', sa.String(), nullable=False),
    sa.Column('haul_type', sa.String(), nullable=False),
    sa.Column('threshold_price_eur', sa.Float(), nullable=True),
    sa.Column('min_abs_savings_eur', sa.Float(), nullable=True),
    sa.Column('min_discount_pct', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('zone')
    )
    op.create_table('deal_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('audience_segment_id', sa.Integer(), nullable=False),
    sa.Column('travel_moment_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('trip_type', sa.String(), nullable=False),
    sa.Column('newsletter_tag', sa.String(), nullable=True),
    sa.Column('public_label', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('included_origins', sa.JSON(), nullable=True),
    sa.Column('included_zones', sa.JSON(), nullable=True),
    sa.Column('included_destinations', sa.JSON(), nullable=True),
    sa.Column('excluded_destinations', sa.JSON(), nullable=True),
    sa.Column('nearby_origins_allowed', sa.Boolean(), nullable=False),
    sa.Column('date_window_type', sa.String(), nullable=False),
    sa.Column('rel_offset_start_days', sa.Integer(), nullable=True),
    sa.Column('rel_offset_end_days', sa.Integer(), nullable=True),
    sa.Column('season_start_mmdd', sa.String(), nullable=True),
    sa.Column('season_end_mmdd', sa.String(), nullable=True),
    sa.Column('fixed_start_date', sa.Date(), nullable=True),
    sa.Column('fixed_end_date', sa.Date(), nullable=True),
    sa.Column('preferred_departure_days', sa.JSON(), nullable=True),
    sa.Column('preferred_return_days', sa.JSON(), nullable=True),
    sa.Column('trip_len_min_days', sa.Integer(), nullable=True),
    sa.Column('trip_len_max_days', sa.Integer(), nullable=True),
    sa.Column('max_price_eur', sa.Float(), nullable=True),
    sa.Column('min_discount_pct', sa.Float(), nullable=True),
    sa.Column('min_abs_savings_eur', sa.Float(), nullable=True),
    sa.Column('psychological_price_threshold_eur', sa.Float(), nullable=True),
    sa.Column('allow_smaller_discount_if_under_price', sa.Boolean(), nullable=False),
    sa.Column('cabin', sa.String(), nullable=False),
    sa.Column('max_stops', sa.Integer(), nullable=True),
    sa.Column('max_total_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('max_layover_minutes', sa.Integer(), nullable=True),
    sa.Column('min_layover_minutes', sa.Integer(), nullable=True),
    sa.Column('allow_overnight_layover', sa.Boolean(), nullable=False),
    sa.Column('allow_airport_change', sa.Boolean(), nullable=False),
    sa.Column('allow_self_transfer', sa.Boolean(), nullable=False),
    sa.Column('allow_mixed_cabin', sa.Boolean(), nullable=False),
    sa.Column('prefer_direct', sa.Boolean(), nullable=False),
    sa.Column('family_friendly_times_only', sa.Boolean(), nullable=False),
    sa.Column('latest_arrival_hour', sa.Integer(), nullable=True),
    sa.Column('earliest_departure_hour', sa.Integer(), nullable=True),
    sa.Column('content_angle', sa.Text(), nullable=True),
    sa.Column('suggested_headline_template', sa.Text(), nullable=True),
    sa.Column('tiktok_hook_template', sa.Text(), nullable=True),
    sa.Column('newsletter_section', sa.String(), nullable=True),
    sa.Column('publish_channel_default', sa.String(), nullable=False),
    sa.Column('rules_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['audience_segment_id'], ['audience_segments.id'], ),
    sa.ForeignKeyConstraint(['travel_moment_id'], ['travel_moments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('routes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('zone', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('cabin', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['zone'], ['zones.zone'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_destination'), 'routes', ['destination'], unique=False)
    op.create_index(op.f('ix_routes_origin'), 'routes', ['origin'], unique=False)
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('zone', sa.String(), nullable=False),
    sa.Column('trip_type', sa.String(), nullable=False),
    sa.Column('travel_date', sa.Date(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('baseline_price', sa.Float(), nullable=True),
    sa.Column('discount_pct', sa.Float(), nullable=True),
    sa.Column('itinerary_snapshot', sa.JSON(), nullable=True),
    sa.Column('search_params', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('scanner_version', sa.String(), nullable=True),
    sa.Column('deal_group_key', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['scan_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_deal_group_key'), 'candidates', ['deal_group_key'], unique=True)
    op.create_table('price_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('trip_type', sa.String(), nullable=False),
    sa.Column('travel_date', sa.Date(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('scanner_version', sa.String(), nullable=False),
    sa.Column('scanned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['scan_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_log_route_id'), 'price_log', ['route_id'], unique=False)
    op.create_index(op.f('ix_price_log_scanned_at'), 'price_log', ['scanned_at'], unique=False)
    op.create_index(op.f('ix_price_log_travel_date'), 'price_log', ['travel_date'], unique=False)
    op.create_table('candidate_template_matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('deal_template_id', sa.Integer(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('reason_text', sa.Text(), nullable=True),
    sa.Column('gate_results', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['deal_template_id'], ['deal_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_template_matches_candidate_id'), 'candidate_template_matches', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_template_matches_deal_template_id'), 'candidate_template_matches', ['deal_template_id'], unique=False)
    op.create_table('content_drafts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('deal_template_id', sa.Integer(), nullable=False),
    sa.Column('headline', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('tiktok_hook', sa.Text(), nullable=True),
    sa.Column('newsletter_snippet', sa.Text(), nullable=True),
    sa.Column('cta_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['deal_template_id'], ['deal_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_drafts_candidate_id'), 'content_drafts', ['candidate_id'], unique=False)
    op.create_table('verification_checks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('booking_url', sa.Text(), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('raw_snapshot', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_checks_candidate_id'), 'verification_checks', ['candidate_id'], unique=False)
    op.create_table('published_deals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('deal_template_id', sa.Integer(), nullable=False),
    sa.Column('content_draft_id', sa.Integer(), nullable=True),
    sa.Column('public_label', sa.String(), nullable=True),
    sa.Column('newsletter_tag', sa.String(), nullable=True),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('tiktok_hook', sa.Text(), nullable=True),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('zone', sa.String(), nullable=True),
    sa.Column('trip_type', sa.String(), nullable=False),
    sa.Column('travel_date', sa.Date(), nullable=True),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('baseline_price', sa.Float(), nullable=True),
    sa.Column('discount_pct', sa.Float(), nullable=True),
    sa.Column('booking_url', sa.Text(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['content_draft_id'], ['content_drafts.id'], ),
    sa.ForeignKeyConstraint(['deal_template_id'], ['deal_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('published_deals')
    op.drop_index(op.f('ix_verification_checks_candidate_id'), table_name='verification_checks')
    op.drop_table('verification_checks')
    op.drop_index(op.f('ix_content_drafts_candidate_id'), table_name='content_drafts')
    op.drop_table('content_drafts')
    op.drop_index(op.f('ix_candidate_template_matches_deal_template_id'), table_name='candidate_template_matches')
    op.drop_index(op.f('ix_candidate_template_matches_candidate_id'), table_name='candidate_template_matches')
    op.drop_table('candidate_template_matches')
    op.drop_index(op.f('ix_price_log_travel_date'), table_name='price_log')
    op.drop_index(op.f('ix_price_log_scanned_at'), table_name='price_log')
    op.drop_index(op.f('ix_price_log_route_id'), table_name='price_log')
    op.drop_table('price_log')
    op.drop_index(op.f('ix_candidates_deal_group_key'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_routes_origin'), table_name='routes')
    op.drop_index(op.f('ix_routes_destination'), table_name='routes')
    op.drop_table('routes')
    op.drop_table('deal_templates')
    op.drop_table('zones')
    op.drop_table('travel_moments')
    op.drop_table('scan_runs')
    op.drop_table('audience_segments')
    # ### end Alembic commands ###
