"""add scan_requests queue table

Revision ID: e2f66796e0e9
Revises: 2d77c318383b
Create Date: 2026-06-03 00:07:54.451694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2f66796e0e9'
down_revision: Union[str, Sequence[str], None] = '2d77c318383b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False, server_default='queued'),
    sa.Column('requested_by', sa.String(), nullable=False, server_default='curator'),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('result_summary', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_requests_created_at'), 'scan_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_scan_requests_status'), 'scan_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_requests_status'), table_name='scan_requests')
    op.drop_index(op.f('ix_scan_requests_created_at'), table_name='scan_requests')
    op.drop_table('scan_requests')
    # ### end Alembic commands ###
